### ISSUE TITLE
Prevent unmount viewmodel with disabled prop in next button

### ISSUE THREAD

**Issue by javieraparisivaldes** [Microsoft/WebTemplateStudio#1263]
Since the step 1 if you double click in next button yo will change to step 3 without selection.

**Steps to reproduce the behavior:**
1.Launch WebTs
2.Double click on next button (fast)
3.Yo will change from step 1 to step 3 without selection, then the extension crash

**Expected behavior**
Until the next step is not ready the next button will be disabled.

**Screenshots**
![vscodebwebts2 (1)](https://user-images.githubusercontent.com/56872233/70030626-e68edc80-15a9-11ea-965b-5f03c183047a.png)

**Additional context**
2019-11-29 12:13:23.940] 681564(1) Verbose Received Command: sync -p ..
[2019-11-29 12:13:32.650] 681564(1) Information Archivo de configuración cargado: c:\Users\\.vscode\extensions\wasteamaccount.webtemplatestudio-dev-nightly-0.0.1929801\src\corets-cli\win32\CoreTemplateStudio.config.json
[2019-11-29 12:14:15.241] 681564(9) Verbose Plantillas extraídas a C:\Users\\AppData\Local\WebTS\Templates\Dev\Web\Any\0.0.19298.1.
[2019-11-29 12:14:47.173]  681564(1) Verbose Received Command: getframeworks -p FullStackWebApp
[2019-11-29 12:14:47.927] 681564(1) Verbose Received Command: getpages -p FullStackWebApp -f  -b
[2019-11-29 12:14:48.560] 681564(1) Critical Seguimiento de la excepción. Error executing Command: getpages -p FullStackWebApp -f  -b .
One or more errors occurred. (Validation failed:
 -- : You must specify a backend or frontend framework at the very least)
===================== Información de excepción =====================
System.AggregateException: One or more errors occurred. (Validation failed:
 -- : You must specify a backend or frontend framework at the very least) ---> FluentValidation.ValidationException: Validation failed:
 -- : You must specify a backend or frontend framework at the very least
   at Microsoft.Templates.Cli.Commands.Handlers.ValidatingHandler`1.ExecuteAsync(T command) in D:\a\1\s\src\CoreTemplateStudio\code\src\CoreTemplateStudio\CoreTemplateStudio.Cli\Commands\Handlers\ValidatingHandler`1.cs:line 32
   at Microsoft.Templates.Cli.Commands.Dispatcher.CommandDispatcher.DispatchAsync[T](T command) in D:\a\1\s\src\CoreTemplateStudio\code\src\CoreTemplateStudio\CoreTemplateStudio.Cli\Commands\Dispatcher\CommandDispatcher.cs:line 32
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Templates.Cli.App.ProcessCommand(String command) in D:\a\1\s\src\CoreTemplateStudio\code\src\CoreTemplateStudio\CoreTemplateStudio.Cli\App.cs:line 65
---> (Inner Exception #0) FluentValidation.ValidationException: Validation failed:
 -- : You must specify a backend or frontend framework at the very least
   at Microsoft.Templates.Cli.Commands.Handlers.ValidatingHandler`1.ExecuteAsync(T command) in D:\a\1\s\src\CoreTemplateStudio\code\src\CoreTemplateStudio\CoreTemplateStudio.Cli\Commands\Handlers\ValidatingHandler`1.cs:line 32
   at Microsoft.Templates.Cli.Commands.Dispatcher.CommandDispatcher.DispatchAsync[T](T command) in D:\a\1\s\src\CoreTemplateStudio\code\src\CoreTemplateStudio\CoreTemplateStudio.Cli\Commands\Dispatcher\CommandDispatcher.cs:line 32<---
**System**

- **VS Code Version:** 1.40.2 
- **WebTS Wizard Version:** 0.0.19298.1
- **WebTS Template Version:** 0.0.19336.1
- **OS:** Windows10

**Comment by sibille** [comment]
Verified in dev-nighlty:

Templates version: 0.1.20056.1
Wizard version: 0.1.2005601
