### ISSUE TITLE
Error generating React Native app on Mac with all pages

### ISSUE THREAD

**Issue by sibille** [Microsoft/WebTemplateStudio#1806]
There is an error when generating a React Native App on Mac with settings page. 
This is due to how files are sorted on Mac. We need to set the compositionOrder here to ensure correct order.

Full Log entry:
```
[2021-05-12 17:27:27.921]	hector	1257(1)		Critical	Exception Tracked. Error executing Command: generate -d {"projectName":"myApp14","genPath":"/Users/hector","projectType":"Tabbed","frontendFramework":"ReactNative","backendFramework":"","language":"Any","platform":"RN","homeName":"Test","pages":[{"name":"Blank","templateid":"wts.RN.Page.Blank"},{"name":"MasterDetail","templateid":"wts.RN.Page.MasterDetail"},{"name":"Settings","templateid":"wts.RN.Page.Settings"}],"features":[]}.
One or more errors occurred. (Error generating. Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.RN.Tabbed.Page.Blank.AddTheme.)
===================== Exception Info =====================
System.AggregateException: One or more errors occurred. (Error generating. Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.RN.Tabbed.Page.Blank.AddTheme.)
 ---> System.Exception: Error generating. Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.RN.Tabbed.Page.Blank.AddTheme.
 ---> System.Exception: Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.RN.Tabbed.Page.Blank.AddTheme.
 ---> System.IO.FileNotFoundException: There is no merge target for file '/Users/hector/myApp14/myApp14/src/navigation/BlankStack_postaction.tsx'. Related Template: 'wts.RN.Tabbed.Page.Blank.AddTheme'.
   at Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction.HandleFileNotFound(String originalFilePath, String suffix)
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   at Microsoft.Templates.Core.Gen.GenController.ExecutePostActions(GenInfo genInfo, TemplateCreationResult generationResult)
   at Microsoft.Templates.Core.Gen.GenController.GenerateItemsAsync(IEnumerable`1 genItems)
   at Microsoft.Templates.Core.Gen.NewProjectGenController.UnsafeGenerateProjectAsync(UserSelection userSelection)
   at Microsoft.Templates.Cli.Services.GenerateService.GenerateAsync(GenerationData generationData)
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Cli.Services.GenerateService.GenerateAsync(GenerationData generationData)
   at Microsoft.Templates.Cli.Commands.Handlers.GenerateHandler.ExecuteAsync(GenerateCommand command)
   at Microsoft.Templates.Cli.Commands.Handlers.ValidatingHandler`1.ExecuteAsync(T command)
   at Microsoft.Templates.Cli.Commands.Dispatcher.CommandDispatcher.DispatchAsync[T](T command)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Templates.Cli.App.ProcessCommand(String command)
```

```
Error generating. Error executing 'Microsoft.Templates.Core.PostActions.Catalog.Merge.MergePostAction'. Related template: wts.RN.Page.AddPicker.)
```

**Comment by sibille** [comment]
Verified on version: 
Templates version: 0.6.21133.1
Wizard version: 0.6.2113301
