### ISSUE TITLE
Running tests on freshly generated React app fails

### ISSUE THREAD

**Issue by jsondoo** [Microsoft/WebTemplateStudio#669]
1. Generate a React app
2. Run `yarn install` then `yarn test` (or npm)

```
 FAIL  src/App.test.js (6.346s)
  × renders without crashing (104ms)

  ● renders without crashing

    Invariant Violation: You should not use <Switch> outside a <Router>

      5 | it('renders without crashing', () => {
      6 |   const div = document.createElement('div');
    > 7 |   ReactDOM.render(<App />, div);
        |            ^
      8 | });
      9 |

      at invariant (node_modules/invariant/invariant.js:40:15)
      at Switch.componentWillMount (node_modules/react-router/Switch.js:46:29)
      at callComponentWillMount (node_modules/react-dom/cjs/react-dom.development.js:11375:14)
      at mountClassInstance (node_modules/react-dom/cjs/react-dom.development.js:11468:5)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14642:5)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15598:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:19266:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:19306:24)
```

**Comment by SahilTara** [comment]
Perhaps adding a < BrowserRouter > wrapping around the < Switch > will help? @jsondoo

**Comment by streetcoder123** [comment]
@SahilTara Is there a reason we don't have it currently?

**Comment by SahilTara** [comment]
not that i know of to be honest
